name: base
channels:
    - defaults
dependencies:
    - python=3.7
      numpy=1.16.2
    - scikit-learn=0.20.3
    - dask=1.1.4
    - dask-ml=0.12.0
    - flask=1.0.2
    - marshmallow=3.0.0
    - pip:
      - leapy>=0.1.0
